name: 'build'

on:
  push:
  pull_request:

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        qt-version: [5.3, 5.4, 5.5, 5.6, 5.11, 5.12]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    # https://github.com/marketplace/actions/install-qt
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt-version }}
    - name: qmake & make
      run: |
        qmake
        make
