name: Build Webpage
on:
  pull_request:
    branches: [ develop ]

defaults:
  run:
    working-directory: webpage

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - id: files
      uses: jitterbit/get-changed-files@v1
    - run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          echo "Do something with this ${changed_file}."
        done
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: yarn install
    - run: yarn run build
